name: PHP Stan

on: [push]

jobs:
  stan-and-tests:
    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [^10.15, ^11.0]

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, zip
          tools: composer:v2
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer install --no-interaction --no-progress

      - name: PHP Stan Analyse
        run: composer analyse
